In [89]:
%matplotlib inline
# Grub AI Notebook
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import RegexpTokenizer
from nltk.tokenize import word_tokenize
from sklearn.cluster import KMeans
import textblob as tb

In [4]:
# Import data
reader = pd.read_json("data/yelp_academic_dataset_review.json", lines=True, chunksize=10000)


In [5]:
#Get dataframe
review_df = None
for chunk in reader:
    review_df = chunk.filter(items=['review_id', 'stars', 'text'])
    break


In [6]:
review_df.head()

review_id  stars  \
0  xQY8N_XvtGbearJ5X4QryQ      2   
1  UmFMZ8PyXZTY2QcwzsfQYA      1   
2  LG2ZaYiOgpr2DK_90pYjNw      5   
3  i6g_oA9Yf9Y31qt0wibXpw      1   
4  6TdNDKywdbjoTkizeMce8A      4   

                                                text  
0  As someone who has worked with many museums, I...  
1  I am actually horrified this place is still in...  
2  I love Deagan's. I do. I really do. The atmosp...  
3  Dismal, lukewarm, defrosted-tasting "TexMex" g...  
4  Oh happy day, finally have a Canes near my cas...

In [61]:
review_df.iloc[[1,5,6]]

review_id  stars  \
1  UmFMZ8PyXZTY2QcwzsfQYA      1   
5  L2O_INwlrRuoX05KSjc4eg      5   
6  ZayJ1zWyWgY9S_TRLT_y9Q      5   

                                                text  
1  I am actually horrified this place is still in...  
5  This is definitely my favorite fast food sub s...  
6  Really good place with simple decor, amazing f...

In [7]:
#tokenize reviews function
snowball = SnowballStemmer('english')
tokenizer = RegexpTokenizer(r'[a-zA-Z\']+')

def tokenize(text):
    return [snowball.stem(word) for word in tokenizer.tokenize(text.lower())]

In [8]:
#vectorize reviews function
def vectorize_reviews(reviews):
    vectorizer = TfidfVectorizer(stop_words = 'english', tokenizer = tokenize, max_features = 1000)
    X = vectorizer.fit_transform(reviews)
    words = vectorizer.get_feature_names()
    return X, words

In [95]:
def print_clusters(company_id, K = 5, num_words = 20):
    labels_color_map = {
        0: '#20b2aa', 1: '#ff7373', 2: '#ffe4e1', 3: '#005073', 4: '#4d0404',
        5: '#ccc0ba', 6: '#4700f9', 7: '#f6f900', 8: '#00f91d', 9: '#da8c49'
    }
    pca_num_components = 2
    company_df = review_df
    # company_name = company_df['name'].unique()[0]
    reviews = company_df['text'].values
    # print(len(reviews))
    # print(reviews)

    X, words = vectorize_reviews(reviews)
    denseX = X.todense()

    






    print(denseX)
    print(denseX.shape)
    # kmeans = KMeans(n_clusters = K)
    # kmeans.fit(X)
    # common_words = kmeans.cluster_centers_.argsort()[:,-1:-num_words-1:-1]
    # print(common_words.shape)
    # print(kmeans.labels_)

    reduced_data = PCA(n_components=3).fit_transform(denseX)
    fig, ax = plt.subplots()
    for index, instance in enumerate(reduced_data):
        # print instance, index, labels[index]
        pca_comp_1, pca_comp_2 = reduced_data[index]
        # color = labels_color_map[kmeans.labels_[index]]
        color = labels_color_map[reviews.iloc[index][1]]
        ax.scatter(pca_comp_1, pca_comp_2, c=color) 
    plt.show()



    # mydict = {i: np.where(kmeans.labels_ == i)[0] for i in range(kmeans.n_clusters)}
    # # print(mydict)
    # # print(kmeans.cluster_centers_.argsort()[:,-1:-num_words-1:-1])
    # # print(len(words))
    # print('Groups of ' + str(num_words) + ' words typically used together in reviews for ' + \
    #       "all businesses")
    # print(mydict[0].tolist())
    # # print()
    # print([company_df.iloc[mydict[key].tolist()]["stars"].mean() for key in mydict.keys()])

    # for num, centroid in enumerate(common_words):
    #     print(str(num) + ' : ' + ', '.join(words[word] for word in centroid))

In [96]:
print_clusters("")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(10000, 1000)


ValueError: too many values to unpack (expected 2)